### ISSUE TITLE
Not providing props field causes crash

### ISSUE THREAD

**Issue by mach-kernel** [mach-kernel/vertx-ext-spa-ssr#5]
```
Apr 05, 2018 12:48:45 PM io.vertx.ext.web.impl.RoutingContextImplBase
SEVERE: Unexpected exception in route
java.lang.NullPointerException
        at io.vertx.ext.web.templ.MessageBackedRenderEngine.lambda$static$0(MessageBackedRenderEngine.java:22)
        at io.vertx.ext.web.templ.impl.MessageBackedRenderEngineImpl.lambda$render$1(MessageBackedRenderEngineImpl.java:133)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4734)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4742)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:747)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:395)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:725)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:430)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:594)
        at io.vertx.ext.web.templ.impl.MessageBackedRenderEngineImpl.render(MessageBackedRenderEngineImpl.java:127)
        at io.vertx.ext.web.templ.impl.MiddlewareStackTemplateEngineImpl.lambda$render$0(MiddlewareStackTemplateEngineImpl.java:57)
```

**Comment by mach-kernel** [comment]
Resolved
